DROP DATABASE IF EXISTS ukolDB;
CREATE DATABASE IF NOT EXISTS ukolDB DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci;

USE ukolDB;

CREATE TABLE contacts(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    fullname VARCHAR(70) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    note TEXT NULL,
    PRIMARY KEY(id)  
);